name: C++ CI Pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Compile OrderBook Unit Tests
          run: g++ -std=c++17 -Iinclude src/OrderBook.cpp tests/test_orderbook.cpp -o run_tests_orderbook

        - name: Run OrderBook Unit Tests
          run: ./run_tests_orderbook

        - name: Compile CSVParser Unit Tests
          run: g++ -std=c++17 -Iinclude src/CSVParser.cpp tests/test_csvparser.cpp -o run_tests_csvparser

        - name: Run CSVParser Unit Tests
          run: ./run_tests_csvparser

        - name: Compile Main Simulator (Verify Build Doesn't Break)
          run: g++ -std=c++17 -O3 -pthread -Iinclude src/*.cpp -o lob_sim

        - name: Compile Cancel Latency Benchmark (Verify Build Doesn't Break)
          run: g++ -std=c++17 -O3 -Iinclude src/OrderBook.cpp benchmarks/bench_cancel.cpp -o bench_cancel